"""
Revision ID: 58920e6807fe
Revises: d2f4a6b8c9d0
Create Date: 2026-02-25 17:56:34.057000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58920e6807fe'
down_revision = 'd2f4a6b8c9d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agents_name_key'), 'agents', type_='unique')
    op.drop_column('agents', 'agent_uuid')
    op.add_column('control_execution_events', sa.Column('agent_name', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_events_data_control_id'), table_name='control_execution_events')
    op.drop_index(op.f('ix_events_agent_time'), table_name='control_execution_events')
    op.create_index('ix_events_agent_time', 'control_execution_events', ['agent_name', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_column('control_execution_events', 'agent_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_execution_events', sa.Column('agent_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index('ix_events_agent_time', table_name='control_execution_events')
    op.create_index(op.f('ix_events_agent_time'), 'control_execution_events', ['agent_uuid', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_events_data_control_id'), 'control_execution_events', [sa.literal_column("(data ->> 'control_id'::text)")], unique=False)
    op.drop_column('control_execution_events', 'agent_name')
    op.add_column('agents', sa.Column('agent_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('agents_name_key'), 'agents', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
