"""
Revision ID: 58e519e06e02
Revises: 53d8427083e2
Create Date: 2026-02-23 13:39:21.295377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58e519e06e02"
down_revision = "53d8427083e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_controls',
    sa.Column('agent_uuid', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_uuid'], ['agents.agent_uuid'], ),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.PrimaryKeyConstraint('agent_uuid', 'control_id')
    )
    op.create_index(op.f('ix_agent_controls_agent_uuid'), 'agent_controls', ['agent_uuid'], unique=False)
    op.create_index(op.f('ix_agent_controls_control_id'), 'agent_controls', ['control_id'], unique=False)
    op.create_table('agent_policies',
    sa.Column('agent_uuid', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_uuid'], ['agents.agent_uuid'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('agent_uuid', 'policy_id')
    )
    op.create_index(op.f('ix_agent_policies_agent_uuid'), 'agent_policies', ['agent_uuid'], unique=False)
    op.create_index(op.f('ix_agent_policies_policy_id'), 'agent_policies', ['policy_id'], unique=False)
    op.execute(
        sa.text(
            """
            INSERT INTO agent_policies (agent_uuid, policy_id)
            SELECT agent_uuid, policy_id
            FROM agents
            WHERE policy_id IS NOT NULL
            ON CONFLICT (agent_uuid, policy_id) DO NOTHING
            """
        )
    )
    op.drop_index(op.f('ix_agents_policy_id'), table_name='agents')
    op.drop_constraint(op.f('agents_policy_id_fkey'), 'agents', type_='foreignkey')
    op.drop_column('agents', 'policy_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Downgrade can only restore one policy per agent via agents.policy_id.
    # If multiple policies were associated to an agent, all but the minimum policy_id are lost.
    op.add_column('agents', sa.Column('policy_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute(
        sa.text(
            """
            UPDATE agents AS a
            SET policy_id = ap.policy_id
            FROM (
                SELECT agent_uuid, MIN(policy_id) AS policy_id
                FROM agent_policies
                GROUP BY agent_uuid
            ) AS ap
            WHERE a.agent_uuid = ap.agent_uuid
            """
        )
    )
    op.create_foreign_key(op.f('agents_policy_id_fkey'), 'agents', 'policies', ['policy_id'], ['id'])
    op.create_index(op.f('ix_agents_policy_id'), 'agents', ['policy_id'], unique=False)
    op.drop_index(op.f('ix_agent_policies_policy_id'), table_name='agent_policies')
    op.drop_index(op.f('ix_agent_policies_agent_uuid'), table_name='agent_policies')
    op.drop_table('agent_policies')
    # NOTE: Direct agent-control associations have no representation in the pre-upgrade schema.
    # Dropping this table intentionally discards those associations during downgrade.
    op.drop_index(op.f('ix_agent_controls_control_id'), table_name='agent_controls')
    op.drop_index(op.f('ix_agent_controls_agent_uuid'), table_name='agent_controls')
    op.drop_table('agent_controls')
    # ### end Alembic commands ###
